Add deploy docu
upb-uc4/deployment pull request #1
Opened 2020-11-26 12:11 UTC by david-buderus

Added basic documentation

2020-11-26 12:21 UTC, lrschaef approved these changes

2020-11-26 12:21 UTC, lrschaef commented on README.md
> +`{}` is a needed parameter.
```suggestion
`{}` is a required parameter.  
```
Sounds better in my opinion. Not a must.

2020-11-26 12:22 UTC, dhelmert requested changes

2020-11-26 12:22 UTC, dhelmert commented on README.md
> +## Remove specific namespaces (and everything their contain)
```suggestion
## Remove specific namespaces (and everything they contain)
```

2020-11-26 12:27 UTC, dhelmert approved these changes

2020-11-27 16:04 UTC, this-kramer approved these changes
I like this docu :+1:

2020-11-30 10:09 UTC, bastihav approved these changes

2020-11-30 10:12 UTC, merged