Add default script
upb-uc4/deployment pull request #2
Opened 2020-12-08 11:25 UTC by david-buderus

Moved default data to an external script

2020-12-08 15:01 UTC, bastihav requested changes

2020-12-08 15:01 UTC, bastihav commented on add_defaults.py
> +post("https://uc4.cs.uni-paderborn.de/api/experimental/course-management/courses", "course", token)
only experimental?

2020-12-08 17:23 UTC, dhelmert approved these changes

2020-12-10 12:31 UTC, this-kramer approved these changes
Good idea. I would like to see more default data for showcasing, i.e. more students, exam regs, ....

2020-12-10 12:31 UTC, this-kramer commented on defaults/user/student.json
> +      "firstName": "Stu",
I would prefer actual names for marketing reasons, the tag student should be sufficient for identifying students.

2020-12-10 12:31 UTC, this-kramer commented on defaults/user/lecturer.json
> +      "firstName": "Lect",
See student name

2020-12-10 16:22 UTC, bastihav approved these changes

2020-12-10 16:22 UTC, bastihav commented on defaults/user/lecturer.json
> +      "email": "jane.doet@mail.de",
```suggestion
      "email": "jane.doe@mail.de",
```

2020-12-10 16:23 UTC, merged